In [156]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
import sklearn.preprocessing as pre
import matplotlib.pyplot as plt

In [157]:
# Using a dummy dataset
dataset = load_diabetes()

In [158]:
X, y = dataset.data, dataset.target

In [159]:
X.shape

(442, 10)

In [160]:
y.shape

(442,)

In [161]:
# Split training and testing data now
# test_size = 0.2 meaning 20% of data is for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [162]:
print(X_train.shape)
print(X_test.shape)

(353, 10)
(89, 10)

In [163]:
print(y_train.shape)
print(y_test.shape)

(353,)
(89,)

In [164]:
# Pandas
import pandas as pd

In [165]:
dataset = pd.read_csv(f'datasets/apple_quality.csv');
dataset

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
0,0.0,-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590483,good
1,1.0,-1.195217,-2.839257,3.664059,1.588232,0.853286,0.867530,-0.722809367,good
2,2.0,-0.292024,-1.351282,-1.738429,-0.342616,2.838636,-0.038033,2.621636473,bad
3,3.0,-0.657196,-2.271627,1.324874,-0.097875,3.637970,-3.413761,0.790723217,good
4,4.0,1.364217,-1.296612,-0.384658,-0.553006,3.030874,-1.303849,0.501984036,good
...,...,...,...,...,...,...,...,...,...
3996,3996.0,-0.293118,1.949253,-0.204020,-0.640196,0.024523,-1.087900,1.854235285,good
3997,3997.0,-2.634515,-2.138247,-2.440461,0.657223,2.199709,4.763859,-1.334611391,bad
3998,3998.0,-4.008004,-1.779337,2.366397,-0.200329,2.161435,0.214488,-2.229719806,good
3999,3999.0,0.278540,-1.715505,0.121217,-1.154075,1.266677,-0.776571,1.599796456,good
4000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Created_by_Nidula_Elgiriyewithana,NaN

In [166]:
dataset.isnull()

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
3996,False,False,False,False,False,False,False,False,False
3997,False,False,False,False,False,False,False,False,False
3998,False,False,False,False,False,False,False,False,False
3999,False,False,False,False,False,False,False,False,False
4000,True,True,True,True,True,True,True,False,True

In [167]:
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [168]:
dataset.iloc[-1:, :1] = dataset.iloc[-1:, :1] = 4000
dataset['Size'] = dataset['Size'].fillna(dataset['Size'].mean())
dataset['Weight'] = dataset['Weight'].fillna(dataset['Weight'].mean())
dataset['Sweetness'] = dataset['Sweetness'].fillna(dataset['Sweetness'].mean())
dataset['Crunchiness'] = dataset['Crunchiness'].fillna(dataset['Crunchiness'].mean())
dataset['Juiciness'] = dataset['Juiciness'].fillna(dataset['Juiciness'].mean())
dataset['Ripeness'] = dataset['Ripeness'].fillna(dataset['Ripeness'].mean())
dataset.iloc[-1:, 7:-1] = dataset.iloc[-2:-1, 7:-1]
dataset.iloc[-1:, -1:] = 'bad'
dataset

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
0,0.0,-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590483,good
1,1.0,-1.195217,-2.839257,3.664059,1.588232,0.853286,0.867530,-0.722809367,good
2,2.0,-0.292024,-1.351282,-1.738429,-0.342616,2.838636,-0.038033,2.621636473,bad
3,3.0,-0.657196,-2.271627,1.324874,-0.097875,3.637970,-3.413761,0.790723217,good
4,4.0,1.364217,-1.296612,-0.384658,-0.553006,3.030874,-1.303849,0.501984036,good
...,...,...,...,...,...,...,...,...,...
3996,3996.0,-0.293118,1.949253,-0.204020,-0.640196,0.024523,-1.087900,1.854235285,good
3997,3997.0,-2.634515,-2.138247,-2.440461,0.657223,2.199709,4.763859,-1.334611391,bad
3998,3998.0,-4.008004,-1.779337,2.366397,-0.200329,2.161435,0.214488,-2.229719806,good
3999,3999.0,0.278540,-1.715505,0.121217,-1.154075,1.266677,-0.776571,1.599796456,good
4000,4000.0,-0.503015,-0.989547,-0.470479,0.985478,0.512118,0.498277,1.599796456,bad

In [169]:
le = LabelEncoder()
dataset['Quality_Enc'] = le.fit_transform(dataset['Quality']).reshape(-1, 1);
dataset

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality,Quality_Enc
0,0.0,-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590483,good,1
1,1.0,-1.195217,-2.839257,3.664059,1.588232,0.853286,0.867530,-0.722809367,good,1
2,2.0,-0.292024,-1.351282,-1.738429,-0.342616,2.838636,-0.038033,2.621636473,bad,0
3,3.0,-0.657196,-2.271627,1.324874,-0.097875,3.637970,-3.413761,0.790723217,good,1
4,4.0,1.364217,-1.296612,-0.384658,-0.553006,3.030874,-1.303849,0.501984036,good,1
...,...,...,...,...,...,...,...,...,...,...
3996,3996.0,-0.293118,1.949253,-0.204020,-0.640196,0.024523,-1.087900,1.854235285,good,1
3997,3997.0,-2.634515,-2.138247,-2.440461,0.657223,2.199709,4.763859,-1.334611391,bad,0
3998,3998.0,-4.008004,-1.779337,2.366397,-0.200329,2.161435,0.214488,-2.229719806,good,1
3999,3999.0,0.278540,-1.715505,0.121217,-1.154075,1.266677,-0.776571,1.599796456,good,1
4000,4000.0,-0.503015,-0.989547,-0.470479,0.985478,0.512118,0.498277,1.599796456,bad,0

In [173]:
dataset['Quality'].unique()
dataset.isna().sum()

A_id           0
Size           0
Weight         0
Sweetness      0
Crunchiness    0
Juiciness      0
Ripeness       0
Acidity        0
Quality        0
Quality_Enc    0
dtype: int64